-- Your SQL goes here
CREATE TABLE  media (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    path VARCHAR(255) UNIQUE NOT NULL, 
    type_ VARCHAR(50) NOT NULL, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);